site_name: "Documentação - 2Do"
theme:
    name: "material"
features:
    - navigation.tabs # Habilita abas de navegação
    - navigation.sections # Habilita a barra lateral de capítulos
nav:
    - "Introdução": docs/index.md
    - "Configuração e Setup": docs/configuracao.md
    - "Estrutura Geral do Projeto": docs/estrutura_projeto.md
    - "Sistema de Gerenciamento de Recursos": docs/assets.md
    - "Entidades e Objetos do Jogo": docs/entidades.md
    - "Sistema de Entrada e Controle": docs/controle.md
    - "Lógica de Jogo e Jogador": docs/logica_jogo.md
    - "Plano de Fundo e Interface": docs/plano_fundo.md
    - "Utilitários e Configuração Adicional": docs/utils.md
    - "Arquivo Principal e Execução": docs/executando.md
    - "Referências e Recursos Adicionais": docs/referencias.md
